site_name: Tài liệu AZtest
site_description: Hệ thống cung cấp Website tổ chức thi, ôn luyện bằng hình thức trắc nghiệm hoàn toàn miễn phí
copyright: AZtest - Hệ thống tạo lập website thi trắc nghiệm trực tuyến miễn phí
site_url: https://docs.aztest.vn
site_author: AZtest
theme:
    name: readthedocs
    custom_dir: themes/aztest/
repo_name: Github
repo_url: https://github.com/mynukeviet/aztest-docs
google_analytics: ['UA-130583769-1', 'docs.aztest.vn']
pages:
- Bắt đầu:
    - Giới thiệu: index.md
    - Khởi tạo website: bat-dau/huong-dan-khoi-tao-website.md
    - Đăng nhập, đăng xuất quản trị: bat-dau/dang-nhap-dang-xuat-quan-tri.md
    - Đổi mật khẩu quản trị: bat-dau/thay-doi-mat-khau-quan-tri.md
    - Thông tin hỗ trợ: bat-dau/thong-tin-ho-tro.md
- Tạo đề thi trắc nghiệm:
    - Xóa dữ liệu mẫu: 'xoa-du-lieu-mau.md'
    - Chủ đề: 'chu-de.md'
    - Xếp loại: 'xep-loai.md'
    - Đề thi: 'de-thi.md'
    - Cấu hình: 'cau-hinh.md'
    - Phân quyền quản lý: 'phan-quyen-quan-ly.md'
- Hướng dẫn:
    - Hướng dẫn mở rộng: huong-dan-mo-rong/index.md
    - Quản trị hệ thống: system.md
